//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Character {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CharacterName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CharacterName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Character.Translate.CharacterName", typeof(CharacterName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปโกรีน.
        /// </summary>
        public static string chara_01_01 {
            get {
                return ResourceManager.GetString("chara_01_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แคล.
        /// </summary>
        public static string chara_01_02 {
            get {
                return ResourceManager.GetString("chara_01_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คกโคโระ.
        /// </summary>
        public static string chara_01_03 {
            get {
                return ResourceManager.GetString("chara_01_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฮิโยริ.
        /// </summary>
        public static string chara_02_01 {
            get {
                return ResourceManager.GetString("chara_02_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยุย.
        /// </summary>
        public static string chara_02_02 {
            get {
                return ResourceManager.GetString("chara_02_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรย์.
        /// </summary>
        public static string chara_02_03 {
            get {
                return ResourceManager.GetString("chara_02_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชิชึรุ.
        /// </summary>
        public static string chara_03_02 {
            get {
                return ResourceManager.GetString("chara_03_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ริโนะ.
        /// </summary>
        public static string chara_03_03 {
            get {
                return ResourceManager.GetString("chara_03_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โนโซมิ.
        /// </summary>
        public static string chara_04_01 {
            get {
                return ResourceManager.GetString("chara_04_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จิกะ.
        /// </summary>
        public static string chara_04_02 {
            get {
                return ResourceManager.GetString("chara_04_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มิมิ.
        /// </summary>
        public static string chara_05_01 {
            get {
                return ResourceManager.GetString("chara_05_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มิโซจิ.
        /// </summary>
        public static string chara_05_03 {
            get {
                return ResourceManager.GetString("chara_05_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาโออิ.
        /// </summary>
        public static string chara_06_01 {
            get {
                return ResourceManager.GetString("chara_06_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฮาสึเนะ.
        /// </summary>
        public static string chara_06_03 {
            get {
                return ResourceManager.GetString("chara_06_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โยริ.
        /// </summary>
        public static string chara_07_02 {
            get {
                return ResourceManager.GetString("chara_07_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาคาริ.
        /// </summary>
        public static string chara_07_03 {
            get {
                return ResourceManager.GetString("chara_07_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชิโนบุ.
        /// </summary>
        public static string chara_07_04 {
            get {
                return ResourceManager.GetString("chara_07_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มิยาโกะ.
        /// </summary>
        public static string chara_07_05 {
            get {
                return ResourceManager.GetString("chara_07_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จุน.
        /// </summary>
        public static string chara_08_01 {
            get {
                return ResourceManager.GetString("chara_08_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ซาเร็น.
        /// </summary>
        public static string chara_09_01 {
            get {
                return ResourceManager.GetString("chara_09_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ศึซึเมะ.
        /// </summary>
        public static string chara_09_02 {
            get {
                return ResourceManager.GetString("chara_09_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุรุมิ.
        /// </summary>
        public static string chara_09_04 {
            get {
                return ResourceManager.GetString("chara_09_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มาโฮะ.
        /// </summary>
        public static string chara_10_01 {
            get {
                return ResourceManager.GetString("chara_10_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มาโคโตะ.
        /// </summary>
        public static string chara_10_02 {
            get {
                return ResourceManager.GetString("chara_10_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คาโอริ.
        /// </summary>
        public static string chara_10_03 {
            get {
                return ResourceManager.GetString("chara_10_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มาฮิรุ.
        /// </summary>
        public static string chara_11_01 {
            get {
                return ResourceManager.GetString("chara_11_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ริมะ.
        /// </summary>
        public static string chara_11_02 {
            get {
                return ResourceManager.GetString("chara_11_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชิโอริ.
        /// </summary>
        public static string chara_11_03 {
            get {
                return ResourceManager.GetString("chara_11_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ริน.
        /// </summary>
        public static string chara_11_04 {
            get {
                return ResourceManager.GetString("chara_11_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อากิโนะ.
        /// </summary>
        public static string chara_12_01 {
            get {
                return ResourceManager.GetString("chara_12_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มิฟุยุ.
        /// </summary>
        public static string chara_12_02 {
            get {
                return ResourceManager.GetString("chara_12_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยูคาริ.
        /// </summary>
        public static string chara_12_03 {
            get {
                return ResourceManager.GetString("chara_12_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทามากิ.
        /// </summary>
        public static string chara_12_04 {
            get {
                return ResourceManager.GetString("chara_12_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มิสึกิ.
        /// </summary>
        public static string chara_13_02 {
            get {
                return ResourceManager.GetString("chara_13_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอริโกะ.
        /// </summary>
        public static string chara_13_03 {
            get {
                return ResourceManager.GetString("chara_13_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อันนะ.
        /// </summary>
        public static string chara_13_05 {
            get {
                return ResourceManager.GetString("chara_13_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อิโอะ.
        /// </summary>
        public static string chara_14_01 {
            get {
                return ResourceManager.GetString("chara_14_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มิซากิ.
        /// </summary>
        public static string chara_14_02 {
            get {
                return ResourceManager.GetString("chara_14_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สึซึนะ.
        /// </summary>
        public static string chara_14_03 {
            get {
                return ResourceManager.GetString("chara_14_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โมนิก้า.
        /// </summary>
        public static string chara_15_01 {
            get {
                return ResourceManager.GetString("chara_15_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยูกิ.
        /// </summary>
        public static string chara_15_02 {
            get {
                return ResourceManager.GetString("chara_15_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นิม่อน.
        /// </summary>
        public static string chara_15_03 {
            get {
                return ResourceManager.GetString("chara_15_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คูกะ.
        /// </summary>
        public static string chara_15_04 {
            get {
                return ResourceManager.GetString("chara_15_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จิต้า.
        /// </summary>
        public static string chara_17_01 {
            get {
                return ResourceManager.GetString("chara_17_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาริสะ.
        /// </summary>
        public static string chara_19_01 {
            get {
                return ResourceManager.GetString("chara_19_01", resourceCulture);
            }
        }
    }
}
