//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Character {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FFAffiliationName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FFAffiliationName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Character.Translate.FFAffiliationName", typeof(FFAffiliationName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อ็อคโต้.
        /// </summary>
        public static string chara_16_01 {
            get {
                return ResourceManager.GetString("chara_16_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คาริน.
        /// </summary>
        public static string chara_16_02 {
            get {
                return ResourceManager.GetString("chara_16_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มุอิมิ.
        /// </summary>
        public static string chara_16_03 {
            get {
                return ResourceManager.GetString("chara_16_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาเมส.
        /// </summary>
        public static string chara_16_04 {
            get {
                return ResourceManager.GetString("chara_16_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไคเซอร์อินไซท์.
        /// </summary>
        public static string chara_18_01 {
            get {
                return ResourceManager.GetString("chara_18_01", resourceCulture);
            }
        }
    }
}
