//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Character {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuildName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuildName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Character.Translate.GuildName", typeof(GuildName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรือนเลิศรส.
        /// </summary>
        public static string guild_name_01 {
            get {
                return ResourceManager.GetString("guild_name_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทวิงเคิลวิช.
        /// </summary>
        public static string guild_name_02 {
            get {
                return ResourceManager.GetString("guild_name_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลาบิรินธ์.
        /// </summary>
        public static string guild_name_03 {
            get {
                return ResourceManager.GetString("guild_name_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คาร์มิน่า.
        /// </summary>
        public static string guild_name_04 {
            get {
                return ResourceManager.GetString("guild_name_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลิตเติ้ลริริคัล.
        /// </summary>
        public static string guild_name_05 {
            get {
                return ResourceManager.GetString("guild_name_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฟอเรสเทียร์.
        /// </summary>
        public static string guild_name_06 {
            get {
                return ResourceManager.GetString("guild_name_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กองทัพราชอาณาจักรปีศาจ (เดียโบลอส).
        /// </summary>
        public static string guild_name_07 {
            get {
                return ResourceManager.GetString("guild_name_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กองอัศวินแห่งวังหลวง (NIGHTMARE).
        /// </summary>
        public static string guild_name_08 {
            get {
                return ResourceManager.GetString("guild_name_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานสงเคราะห์ซาเรนเดีย.
        /// </summary>
        public static string guild_name_09 {
            get {
                return ResourceManager.GetString("guild_name_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน่วยลาดตระเวน (คาออน).
        /// </summary>
        public static string guild_name_10 {
            get {
                return ResourceManager.GetString("guild_name_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ฟาร์มปศุสัตว์ (อลิซาเบธปาร์ค).
        /// </summary>
        public static string guild_name_11 {
            get {
                return ResourceManager.GetString("guild_name_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มกองทุนเมอร์คิวเรียส.
        /// </summary>
        public static string guild_name_12 {
            get {
                return ResourceManager.GetString("guild_name_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทไวไลท์คาราวาน.
        /// </summary>
        public static string guild_name_13 {
            get {
                return ResourceManager.GetString("guild_name_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วิทยาลัยลูเซนต์.
        /// </summary>
        public static string guild_name_14 {
            get {
                return ResourceManager.GetString("guild_name_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไวซ์ฟลูเกล สาขาแลนด์โซล.
        /// </summary>
        public static string guild_name_15 {
            get {
                return ResourceManager.GetString("guild_name_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        public static string guild_name_17 {
            get {
                return ResourceManager.GetString("guild_name_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        public static string guild_name_19 {
            get {
                return ResourceManager.GetString("guild_name_19", resourceCulture);
            }
        }
    }
}
